[package]
name = "mc-whitelister"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
may_minihttp = "0.1"
mc-rcon = "0.1"
lazy_static = "1.5"
sailfish = "0.9"
include-dir-macro = "0.2"
